"""Add image_url to Product

Revision ID: 448489b61b7a
Revises: 46f50459a8d8
Create Date: 2024-07-11 17:10:00.084784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448489b61b7a'
down_revision = '46f50459a8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_url')
    # ### end Alembic commands ###
